sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t shoginn/raspbian-dump1090 ./dump1090
- docker build -t shoginn/shoginn/raspbian-flightaware ./flightaware
- docker build -t shoginn/raspbian-flightradar24 ./flightradar
- docker build -t shoginn/raspbian-planefinder ./planefinder

# push image
#- >
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push shoginn/raspbian-dump1090
    docker push shoginn/shoginn/raspbian-flightaware
    docker push shoginn/raspbian-flightradar24
    docker push shoginn/raspbian-planefinder
